version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html

  laravel:
    image: your_laravel_image
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - nginx

