version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: desafio_db
      MYSQL_USER: angelosouza
      MYSQL_PASSWORD: .Angelo1
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    restart: always
    depends_on:
      - mysql
    volumes:
      - .:/app
    environment:
      DB_HOST: mysql
      DB_USER: angelosouza
      DB_PASSWORD: .Angelo1
      DB_DATABASE: desafio_db
    command: ["./wait-for-it.sh", "mysql:3306", "--", "npm", "start"]

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  mysql_data:

